id: P009231
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-19 19:29:09.112774
source_metadata:
  id: bdr:W22174
  title: བོད་ཡིག་བརྡ་སྤྲོད་སྐྱར་སྦྱོང་དྲི་བ་དང་དྲིས་ལན
  author: ''
  volumes:
    f4e7b25c6ea04b4ba67a8dbdfb6eb340:
      image_group_id: I4739
      title: ''
      volume_number: 1
      total_pages: 118
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
