id: I19B251AA
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T06:53:52+00:00'
last_modified: '2022-06-08T09:32:55.713169+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W22174
  title: བོད་ཡིག་བརྡ་སྤྲོད་སྐྱར་སྦྱོང་དྲི་བ་དང་དྲིས་ལན
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    C3AA:
      image_group_id: I4739
      title: ''
      total_pages: 118
      order: 1
      base_file: C3AA.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
